export const Users = [
  {
    id:1,
    profilePicture: "pp/pp1.jpeg",
    username: "John Cena",
  },
  {
    id:2,
    profilePicture: "pp/pp2.jpeg",
    username: "Roman Reigns",
  },
  {
    id:3,
    profilePicture: "pp/pp3.jpeg",
    username: "Seth Rollins",
  },
  {
    id:4,
    profilePicture: "pp/pp4.jpeg",
    username: "Dean Ambrose",
  },
  {
    id:5,
    profilePicture: "pp/pp5.jpeg",
    username: "Jon Moxley",
  },
  {
    id:6,
    profilePicture: "pp/pp1.jpeg",
    username: "CM Punk",
  },
  {
    id:7,
    profilePicture: "pp/pp2.jpeg",
    username: "Randy Orton",
  },
  {
    id:8,
    profilePicture: "pp/pp3.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "pp/pp4.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "pp/pp5.jpeg",
    username: "James King",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/post6.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/post8.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/post9.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/post4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/post1.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/post2.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/post4.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/post3.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/post5.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
    id: 10,
    photo: "post/post6.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
